//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by InjDemo.rc
//
#define IDC_LIST                        1000
#define IDC_EDIT                        1001
#define IDC_INJTYPE                     1002
#define IDC_DLLTYPE                     1003
#define IDC_SUBCTYPE                    1004
#define IDC_DLLPATH                     1015
#define IDC_BROWSE                      1017
#define IDC_INJECT                      1019
#define IDC_EJECT                       1020
#define IDC_INJCODE                     1021
#define IDC_INJDLL                      1022
#define IDC_SUBCLASS                    1023
#define IDC_START                       1024
#define IDC_STOP                        1025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
